# netlify.toml

[build]
  # Directory to which the build command will output files.
  publish = "build"

  # Your build command here.
  command = "npm run build"

  # Environment variables.
  [build.environment]
    NODE_VERSION = "16"

# Redirects and Rewrites.
# Uncomment and modify the following section if you need redirects or rewrites.
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Custom headers.
# Uncomment and modify the following section if you need custom headers.
# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Frame-Options = "DENY"
#     X-XSS-Protection = "1; mode=block"
